name: binp28_transcriptomics_local
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - _r-mutex=1.0.1=anacondar_1
  - argcomplete=3.6.3=pyhd8ed1ab_0
  - bioconductor-biobase=2.66.0=r44h1b44f6e_0
  - bioconductor-biocgenerics=0.52.0=r44hdfd78af_3
  - bioconductor-biocparallel=1.40.0=r44hb11b259_1
  - bioconductor-data-packages=20250625=hdfd78af_0
  - bioconductor-delayedarray=0.32.0=r44h1b44f6e_1
  - bioconductor-deseq2=1.46.0=r44hb11b259_1
  - bioconductor-genomeinfodb=1.42.0=r44hdfd78af_2
  - bioconductor-genomeinfodbdata=1.2.13=r44hdfd78af_0
  - bioconductor-genomicranges=1.58.0=r44h1b44f6e_2
  - bioconductor-iranges=2.40.0=r44h1b44f6e_2
  - bioconductor-matrixgenerics=1.18.0=r44hdfd78af_0
  - bioconductor-s4arrays=1.6.0=r44h1b44f6e_1
  - bioconductor-s4vectors=0.44.0=r44h1b44f6e_2
  - bioconductor-sparsearray=1.6.0=r44h1b44f6e_1
  - bioconductor-summarizedexperiment=1.36.0=r44hdfd78af_0
  - bioconductor-ucsc.utils=1.2.0=r44hdfd78af_0
  - bioconductor-xvector=0.46.0=r44h5badf08_2
  - bioconductor-zlibbioc=1.52.0=r44h1b44f6e_2
  - bwidget=1.10.1=hce30654_1
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.6=hc919400_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h6a3b0d2_0
  - cctools=1030.6.3=llvm21_1_h8e84c17_4
  - cctools_impl_osx-arm64=1030.6.3=llvm21_1_h7a537a9_4
  - cctools_osx-arm64=1030.6.3=llvm21_1_h6d92914_4
  - clang=21.1.8=default_cfg_hb78b91e_2
  - clang-21=21.1.8=default_hb52604d_2
  - clang_impl_osx-arm64=21.1.8=default_h17d1ed9_2
  - clang_osx-arm64=21.1.8=h15b5089_31
  - clangxx_impl_osx-arm64=21.1.8=default_h17d1ed9_2
  - clangxx_osx-arm64=21.1.8=h15b5089_31
  - compiler-rt=21.1.8=hce30654_1
  - compiler-rt21=21.1.8=h855ad52_1
  - compiler-rt21_osx-arm64=21.1.8=h2514db7_1
  - compiler-rt_osx-arm64=21.1.8=hce30654_1
  - curl=8.18.0=he38603e_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.16=hc919400_0
  - gfortran_impl_osx-arm64=14.3.0=h6d03799_1
  - gfortran_osx-arm64=14.3.0=h3c33bd0_0
  - gmp=6.3.0=h7bae524_2
  - graphite2=1.3.14=hec049ff_2
  - gsl=2.7=h6e638da_0
  - harfbuzz=12.2.0=haf38c7b_0
  - icu=75.1=hfee45f7_0
  - isl=0.26=imath32_h347afa1_101
  - jq=1.8.1=hbc156a2_0
  - krb5=1.21.3=h237132a_0
  - ld64=956.6=llvm21_1_h5d6df6c_4
  - ld64_osx-arm64=956.6=llvm21_1_h3eeb6b3_4
  - lerc=4.0.0=hd64df32_1
  - libasprintf=0.25.1=h493aca8_0
  - libblas=3.11.0=5_h51639a9_openblas
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libclang-cpp21.1=21.1.8=default_hf3020a7_2
  - libcompiler-rt=21.1.8=h855ad52_1
  - libcurl=8.18.0=he38603e_0
  - libcxx=21.1.8=hf598326_1
  - libcxx-devel=21.1.8=h6dc3340_1
  - libcxx-headers=21.1.8=h707e725_1
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=hcf2aa1b_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_16
  - libgettextpo=0.25.1=h493aca8_0
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran-devel_osx-arm64=14.3.0=hc965647_1
  - libgfortran5=15.2.0=hdae7583_16
  - libglib=2.86.3=hfe11c1f_0
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=5_hd9741b5_openblas
  - libllvm21=21.1.8=h8e0c9ce_0
  - liblzma=5.8.2=h8088a28_0
  - libmpdec=4.0.0=h84a0fba_1
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_4
  - libpng=1.6.54=h132b30e_0
  - libsigtool=0.1.3=h98dc951_0
  - libsqlite=3.51.2=h1b79a29_0
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.1=h4030677_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxml2=2.15.1=h9329255_0
  - libxml2-16=2.15.1=h0ff4647_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.8=h4a912ad_0
  - llvm-tools=21.1.8=h855ad52_0
  - llvm-tools-21=21.1.8=h91fd4e7_0
  - make=4.4.1=hc9fafa5_2
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - ncurses=6.5=h5e97a16_3
  - oniguruma=6.9.10=h5505292_0
  - openssl=3.6.1=hd24854e_1
  - pango=1.56.4=h875632e_0
  - pcre2=10.47=h30297fc_0
  - pip=26.0=pyh145f28c_0
  - pixman=0.46.4=h81086ad_1
  - python=3.14.2=h40d2674_101_cp314
  - python_abi=3.14=8_cp314
  - pyyaml=6.0.3=pyh7db6752_0
  - r-abind=1.4_8=r44hc72bb7e_1
  - r-askpass=1.2.1=r44h6168396_1
  - r-base=4.4.3=hb2e0d2d_7
  - r-bh=1.87.0_1=r44hc72bb7e_1
  - r-cli=3.6.5=r44hc1cd577_1
  - r-codetools=0.2_20=r44hc72bb7e_2
  - r-colorspace=2.1_2=r44h6168396_0
  - r-cpp11=0.5.3=r44h785f33e_0
  - r-crayon=1.5.3=r44hc72bb7e_2
  - r-curl=7.0.0=r44hbc3244a_1
  - r-farver=2.1.2=r44hc1cd577_2
  - r-formatr=1.14=r44hc72bb7e_3
  - r-futile.logger=1.4.9=r44hc72bb7e_0
  - r-futile.options=1.0.1=r44hc72bb7e_1006
  - r-ggplot2=4.0.1=r44h785f33e_0
  - r-glue=1.8.0=r44h6168396_1
  - r-gtable=0.3.6=r44hc72bb7e_1
  - r-httr=1.4.7=r44hc72bb7e_2
  - r-isoband=0.3.0=r44hc1cd577_0
  - r-jsonlite=2.0.0=r44h6168396_1
  - r-labeling=0.4.3=r44hc72bb7e_2
  - r-lambda.r=1.2.4=r44hc72bb7e_5
  - r-lattice=0.22_7=r44h6168396_1
  - r-lifecycle=1.0.5=r44hc72bb7e_0
  - r-locfit=1.5_9.12=r44h6168396_1
  - r-matrix=1.7_4=r44hb2d3ebe_1
  - r-matrixstats=1.5.0=r44h6168396_1
  - r-mime=0.13=r44h6168396_1
  - r-munsell=0.5.1=r44hc72bb7e_2
  - r-openssl=2.3.4=r44h7a56cc5_0
  - r-r6=2.6.1=r44hc72bb7e_1
  - r-rcolorbrewer=1.1_3=r44h785f33e_4
  - r-rcpp=1.1.1=r44h1380947_0
  - r-rcpparmadillo=15.2.3_1=r44ha64934e_0
  - r-rlang=1.1.7=r44h1380947_0
  - r-s7=0.2.1=r44h6168396_0
  - r-scales=1.4.0=r44hc72bb7e_1
  - r-snow=0.4_4=r44hc72bb7e_4
  - r-sys=3.4.3=r44h6168396_1
  - r-vctrs=0.7.1=r44h1380947_0
  - r-viridislite=0.4.2=r44hc72bb7e_3
  - r-withr=3.0.2=r44hc72bb7e_1
  - readline=8.3=h46df422_0
  - sdkroot_env_osx-arm64=26.0=ha3f98da_6
  - setuptools=80.10.2=pyh332efcf_0
  - sigtool-codesign=0.1.3=h98dc951_0
  - tapi=1600.0.11.8=h997e182_0
  - tk=8.6.13=h010d191_3
  - tktable=2.10=h3c7de25_7
  - toml=0.10.2=pyhcf101f3_3
  - tomlkit=0.14.0=pyha770c72_0
  - tzdata=2025c=hc9c84f9_1
  - xmltodict=1.0.2=pyhcf101f3_0
  - yaml=0.2.5=h925e9cb_3
  - yq=3.4.3=pyhe01879c_2
  - zlib=1.3.1=h8359307_2
  - zstd=1.5.7=hbf9d68e_6
prefix: /Users/otodreas/miniconda3/envs/binp28_transcriptomics_local
