name: snakemake
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - amply=0.1.6=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - appdirs=1.4.4=pyhd8ed1ab_1
  - argparse-dataclass=2.0.0=pyhd8ed1ab_1
  - attrs=25.4.0=pyhcf101f3_1
  - backports.zstd=1.3.0=py313h18e8e13_0
  - brotli-python=1.2.0=py313hf159716_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - coin-or-cbc=2.10.12=h4d16d09_5
  - coin-or-cgl=0.60.9=hc46dffc_7
  - coin-or-clp=1.17.10=hc03379b_4
  - coin-or-osi=0.108.11=hf4fecb4_8
  - coin-or-utils=2.11.12=hc93afbd_7
  - colorama=0.4.6=pyhd8ed1ab_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - conda-inject=1.3.2=pyhd8ed1ab_0
  - configargparse=1.7.1=pyhe01879c_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - docutils=0.22.4=pyhd8ed1ab_0
  - dpath=2.2.0=pyha770c72_1
  - eido=0.2.5=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.46=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - humanfriendly=10.0=pyh707e725_8
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - immutables=0.21=py313h07c4f96_2
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhcf101f3_1
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcblas=3.11.0=5_h0358290_openblas
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libgcc=15.2.0=he0feb66_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblapacke=3.11.0=5_h6ae95b6_openblas
  - liblzma=5.8.2=hb03c661_0
  - libmpdec=4.0.0=hb03c661_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_16
  - libuuid=2.41.3=h5347b49_0
  - libzlib=1.3.1=hb9d3cd8_2
  - logmuse=0.2.8=pyhd8ed1ab_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py313h3dea7bd_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - numpy=2.4.2=py313hf6604e3_1
  - openssl=3.6.1=h35e630c_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py313h08cd8bf_2
  - pephubclient=0.4.4=pyhd8ed1ab_1
  - peppy=0.40.8=pyhd8ed1ab_0
  - pip=26.0=pyh145f28c_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - pluggy=1.6.0=pyhf9edf01_1
  - psutil=7.2.2=py313h54dd161_0
  - pulp=2.8.0=py313hf1034c9_3
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py313h843e2db_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=9.0.2=pyhcf101f3_0
  - python=3.13.11=hc97d973_101_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.13=8_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py313h3dea7bd_1
  - readline=8.3=h853b02a_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - reretry=0.11.8=pyhd8ed1ab_1
  - rich=14.3.2=pyhcf101f3_0
  - rpds-py=0.30.0=py313h843e2db_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - slack-sdk=3.39.0=pyhd8ed1ab_0
  - slack_sdk=3.39.0=hd8ed1ab_0
  - smart_open=7.5.0=pyhcf101f3_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snakemake=9.16.2=hdfd78af_1
  - snakemake-interface-common=1.22.0=pyhd4c3c12_0
  - snakemake-interface-executor-plugins=9.3.9=pyhdfd78af_0
  - snakemake-interface-logger-plugins=2.0.0=pyhd4c3c12_0
  - snakemake-interface-report-plugins=1.3.0=pyhd4c3c12_0
  - snakemake-interface-scheduler-plugins=2.0.2=pyhd4c3c12_0
  - snakemake-interface-storage-plugins=4.3.2=pyhd4c3c12_0
  - snakemake-minimal=9.16.2=pyhdfd78af_1
  - tabulate=0.9.0=pyhcf101f3_3
  - throttler=1.2.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h366c992_103
  - tomli=2.4.0=pyhcf101f3_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typer=0.21.1=pyhf8876ea_0
  - typer-slim=0.21.1=pyhcf101f3_0
  - typer-slim-standard=0.21.1=h378290b_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - ubiquerg=0.8.0=pyhd8ed1ab_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wrapt=1.17.3=py313h07c4f96_1
  - yaml=0.2.5=h280c20c_3
  - yte=1.9.4=pyhd8ed1ab_0
  - zstd=1.5.7=hb78ec9c_6
prefix: /home/inf-33-2025/miniconda3/envs/snakemake
